# Introduction

In [2]:
import numpy as np

**Creating 1D array and trying out different functions**

In [11]:
arr = np.array([3,4,6,7,3,9,8,4,1],np.int64)

5


In [8]:
arr[0]

3

In [9]:
arr[3]

9

In [14]:
arr.shape

(5,)

In [18]:
arr.size

5

In [26]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
arr = np.linspace(1,5,4)#4 elements equally spaced starting from 1 and ending with 5
print(arr)

[1.         2.33333333 3.66666667 5.        ]
3


In [5]:
arr = np.arange(20)
print(f"Before = {arr}")
arr = arr.reshape(4,5)
print(f"After reshape = {arr}")
arr = arr.ravel()
print(f"After ravel = {arr}")

Before = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After reshape = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
After ravel = [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**Creating 2D array and trying out different functions**

In [48]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int64)
print(arr2D)
arr2DTranspose = arr2D.T
print(f"\n{arr2DTranspose}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
arr = np.array([7,8,6,3],np.int32)#try np.int64
maxIndex = arr.argmax()#gives index of max value
minIndex = arr.argmin()#gives index of min value
sortIndexList = arr.argsort()#returns list index for sorted order
print(arr.nbytes)#gives number of bytes for arr 4*5=20 in this case
print(maxIndex)
print(minIndex)
print(sortIndexList)

16
1
3
[3 2 0 1]


In [24]:
arr2D = np.array([[3,1,2],
                  [1,10,2],
                  [5,2,8]],np.int32)
maxIndex = arr2D.argmax()
minIndex = arr2D.argmin()
sortedIndexList = arr2D.argsort()#returns list index for sorted order
verticalAxis = arr2D.argmax(axis=0)#returns max value index for vertical axes
horizontalAxis = arr2D.argmax(axis=1)#returns max value index for 
print(maxIndex)
print(minIndex)
print(sortedIndexList)
print(verticalAxis)
print(horizontalAxis)

4
1
[[1 2 0]
 [0 2 1]
 [1 0 2]]
[2 1 2]
[0 1 2]


In [40]:
arr1 = np.array([[5,7,3],
                [0,6,5],
                [3,2,2]])

arr2 = np.array([[7,8,2],
                [3,6,6],
                [2,5,9]])

sum = arr1+arr2
diff = arr1-arr2
prod = arr1*arr2

print(sum,end="\n\n")
print(diff,end="\n\n")
print(prod,end="\n\n")
print(np.sqrt(arr1),end="\n\n")    #Gives square root of all elements of arr1
print(np.where(arr1>3),end="\n\n") #Gives index of all elements greater than 3
print(np.nonzero(arr1))            #Returns all the index where elements are not zero

print(arr1.sum(),end="\n\n")       #Gives sum of all elements of arr1 
print(arr1.max(),end="\n\n")       #Gives max of all the elements of arr1
print(arr1.min(),end="\n\n")       #Gives min of all the elements of arr1


[[12 15  5]
 [ 3 12 11]
 [ 5  7 11]]

[[-2 -1  1]
 [-3  0 -1]
 [ 1 -3 -7]]

[[35 56  6]
 [ 0 36 30]
 [ 6 10 18]]

[[2.23606798 2.64575131 1.73205081]
 [0.         2.44948974 2.23606798]
 [1.73205081 1.41421356 1.41421356]]

(array([0, 0, 1, 1]), array([0, 1, 1, 2]))

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 1, 2, 0, 1, 2]))
33

7

0



In [7]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int64)
print(arr2D,end="\n\n")

arr2DFlat = arr2D.flat  
for item in arr2DFlat:
    print(item,end=" ")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1 2 3 4 5 6 7 8 9 

In [13]:
arr2D.shape

(3, 3)

In [17]:
arr2D[2,2] = 99
print(arr2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]]


In [45]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]],np.int64)
colSum = arr2D.sum(axis = 0)
rowSum = arr2D.sum(axis = 1)
print(colSum)
print(rowSum)

[12 15 18]
[ 6 15 24]


In [19]:
arr2D.size

9

In [20]:
arr2D.dtype

dtype('int64')

In [59]:
arr2D = np.identity(10)#gives an identity matrix of 10X10
print(arr2D)
print(arr2D.ndim)#prints the dimension of the array
print(arr.ndim)#prints the dimension of the array

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
2
1


In [24]:
arr2D = np.zeros((3,4),np.int32)#By default it is float

In [22]:
print(arr2D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
arr2D.dtype

dtype('int32')